package com.pewick.mcocktailapp.datamodels

import com.squareup.moshi.Json

data class DrinkDetails(
    @field:Json(name = "idDrink") val id: String,
    @field:Json(name = "strDrink") val name: String,
    @field:Json(name = "strDrinkThumb") val imageUrl: String,
    @field:Json(name = "strGlass") val glass: String,
    @field:Json(name = "strAlcoholic") val alcoholic: String,
    @field:Json(name = "strCategory") val category: String,
    @field:Json(name = "strInstructions") val instructions: String,
    @field:Json(name = "strIngredient1") val ingredient1: String?,
    @field:Json(name = "strIngredient2") val ingredient2: String?,
    @field:Json(name = "strIngredient3") val ingredient3: String?,
    @field:Json(name = "strIngredient4") val ingredient4: String?,
    @field:Json(name = "strIngredient5") val ingredient5: String?,
    @field:Json(name = "strIngredient6") val ingredient6: String?,
    @field:Json(name = "strIngredient7") val ingredient7: String?,
    @field:Json(name = "strIngredient8") val ingredient8: String?,
    @field:Json(name = "strIngredient9") val ingredient9: String?,
    @field:Json(name = "strIngredient10") val ingredient10: String?,
    @field:Json(name = "strIngredient11") val ingredient11: String?,
    @field:Json(name = "strIngredient12") val ingredient12: String?,
    @field:Json(name = "strIngredient13") val ingredient13: String?,
    @field:Json(name = "strIngredient14") val ingredient14: String?,
    @field:Json(name = "strIngredient15") val ingredient15: String?,
    @field:Json(name = "strMeasure1") val measure1: String?,
    @field:Json(name = "strMeasure2") val measure2: String?,
    @field:Json(name = "strMeasure3") val measure3: String?,
    @field:Json(name = "strMeasure4") val measure4: String?,
    @field:Json(name = "strMeasure5") val measure5: String?,
    @field:Json(name = "strMeasure6") val measure6: String?,
    @field:Json(name = "strMeasure7") val measure7: String?,
    @field:Json(name = "strMeasure8") val measure8: String?,
    @field:Json(name = "strMeasure9") val measure9: String?,
    @field:Json(name = "strMeasure10") val measure10: String?,
    @field:Json(name = "strMeasure11") val measure11: String?,
    @field:Json(name = "strMeasure12") val measure12: String?,
    @field:Json(name = "strMeasure13") val measure13: String?,
    @field:Json(name = "strMeasure14") val measure14: String?,
    @field:Json(name = "strMeasure15") val measure15: String?)
